accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

django_quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('roomapp.urls')),
    path('accounts/',include('accountapp.urls')),
]

roomapp/urls.py
from django.urls import path

from roomapp import views
from roomapp.views import RoomsView

app_name = "roomapp"

urlpatterns = [
    path('', RoomsView.as_view(), name='rooms'),
    path('<slug:slug>/', views.room, name='room'),
]

accountapp/models.py
from django.db import models

# Create your models here.

roomapp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Room(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm

has_ownership = [account_ownership_required, login_required]
# Create your views here.

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = 25


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

roomapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from roomapp.models import Room, Message


# Create your views here.
class RoomsView(ListView):
    model = Room
    template_name = 'roomapp/rooms.html'
    context_object_name = 'rooms'
    page_kwarg = 'page'


@login_required
def room(request, slug):
    room = Room.objects.get(slug=slug)
    messages = Message.objects.filter(room=room)[0:25]

    return render(request, 'roomapp/room.html', {'room': room, 'messages': messages})

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
      <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
      <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
      <p>
        {{ target_user.date_joined }}
      </p>
    </div>
  </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div>
      <h4>Login</h4>
    </div>
    <div>
      <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
      </form>
    </div>
  </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
      <h4>Change Info</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

roomapp/templates/roomapp/room.html
{% extends 'base.html' %}

{% block title %} {{ room.name }} | {% endblock %}

{% block content %}
<div class="container p-5 text-center">
    <h1 class="display-4 text-white">{{ room.name }}</h1>
</div>

<div class="container-lg my-4">
    <div class="card bg-light rounded-xl">
        <div class="card-body">
            <div class="chat-messages space-y-3" id="chat-messages">
                {% for m in messages %}
                <div class="mb-2">
                    <strong>{{ m.user.username }}</strong>: {{ m.content }}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="container-lg my-4">
    <form action="." method="post" class="d-flex">
        {% csrf_token %}
        <input type="text" name="content" class="form-control flex-grow-1 me-3" id="chat-message-input">
        <button class="btn btn-primary rounded-xl" id="chat-message-submit">전송</button>
    </form>
</div>
{% endblock %}

{% block script %}
{{ room.slug|json_script:"json-roomname" }}
{{ request.user.username|json_script:"json-username" }}

<script>
    const roomName = JSON.parse(document.getElementById("json-roomname").textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);
    const chatSocket = new WebSocket(
        "ws://"
        + window.location.host
        + "/ws/"
        + roomName
        + "/"
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);

        if (data.message) {
            document.querySelector('#chat-messages').innerHTML += ('<b>' + data.username + '</b>: ' + data.message + '<br>');
        } else {
            console.log("값 공백");
        }

        scrollToBottom();
    };

    document.querySelector('#chat-message-input').focus();

    chatSocket.onclose = function(e) {
        console.log('onclose');
        console.log(e.code);
    }

    document.querySelector('#chat-message-submit').onclick = function(e) {
        e.preventDefault()

        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;

        if (message.trim().length === 0) {
            return false
        }

        console.log({
            'message': message,
            'username': userName,
            'room': roomName
        })

        chatSocket.send(JSON.stringify({
            'message': message,
            'username': userName,
            'room': roomName
        }));

        messageInputDom.value = '';

        return false
    }

    /**
    * A function for finding the messages element, and scroll to the bottom of it.
    */
    function scrollToBottom() {
        let objDiv = document.getElementById("chat-messages");
        objDiv.scrollTop = objDiv.scrollHeight;
    }

    // Add this below the function to trigger the scroll on load.
    scrollToBottom();
</script>
{% endblock %}

roomapp/templates/roomapp/rooms.html
{% extends 'base.html' %}

{% block title %}Rooms | {% endblock %}

{% block content %}
<div class="container p-5 text-center">
    <h1 class="display-4 text-white">Rooms</h1>
</div>

<div class="container">
    <div class="row">
        {% for room in rooms %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card bg-white shadow rounded-xl">
                <div class="card-body">
                    <h2 class="card-title text-2xl font-semibold">{{ room.name }}</h2>
                    <a href="{% url 'roomapp:room' room.slug %}" class="btn btn-primary rounded-xl">Join</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <nav>
      <div>
        <a href="">Home</a>
        <a href="">Characters</a>
        <a href="{% url 'roomapp:rooms' %}">Games</a>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% block script %}
    {% endblock %}
  </body>
</html>